"""Creacion inicial tablas usuarios, clientes, productos

Revision ID: 1ca091627be3
Revises: 
Create Date: 2025-06-01 17:58:36.587204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca091627be3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=True),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=50), nullable=False),
    sa.Column('notas_cliente', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_apellidos'), ['apellidos'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_fecha_registro'), ['fecha_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_tipo_cliente'), ['tipo_cliente'], unique=False)

    op.create_table('productos',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('precio_base_kg', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_activo'))

    op.drop_table('usuarios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))
        batch_op.drop_index(batch_op.f('ix_productos_categoria'))
        batch_op.drop_index(batch_op.f('ix_productos_activo'))

    op.drop_table('productos')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_tipo_cliente'))
        batch_op.drop_index(batch_op.f('ix_clientes_nombre'))
        batch_op.drop_index(batch_op.f('ix_clientes_fecha_registro'))
        batch_op.drop_index(batch_op.f('ix_clientes_apellidos'))
        batch_op.drop_index(batch_op.f('ix_clientes_alias'))
        batch_op.drop_index(batch_op.f('ix_clientes_activo'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
