"""Modelos detallados de producto, subproducto, modificacion, precio y tablas de asociacion

Revision ID: 6ca58832193c
Revises: 1ca091627be3
Create Date: 2025-06-01 18:57:37.651706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca58832193c'
down_revision = '1ca091627be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_modif', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modificaciones_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_modificaciones_codigo_modif'), ['codigo_modif'], unique=True)
        batch_op.create_index(batch_op.f('ix_modificaciones_nombre'), ['nombre'], unique=False)

    op.create_table('producto_modificacion_association',
    sa.Column('producto_id', sa.String(length=10), nullable=False),
    sa.Column('modificacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modificacion_id'], ['modificaciones.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'modificacion_id')
    )
    op.create_table('subproductos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_padre_id', sa.String(length=10), nullable=False),
    sa.Column('codigo_subprod', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['producto_padre_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subproductos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subproductos_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_subproductos_codigo_subprod'), ['codigo_subprod'], unique=True)
        batch_op.create_index(batch_op.f('ix_subproductos_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_subproductos_producto_padre_id'), ['producto_padre_id'], unique=False)

    op.create_table('precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.String(length=10), nullable=True),
    sa.Column('subproducto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=50), nullable=False),
    sa.Column('precio_kg', sa.Float(), nullable=False),
    sa.Column('cantidad_minima_kg', sa.Float(), nullable=False),
    sa.Column('etiqueta_promo', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('fecha_fin_vigencia', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(producto_id IS NOT NULL AND subproducto_id IS NULL) OR (producto_id IS NULL AND subproducto_id IS NOT NULL)', name='chk_precio_target_not_both_or_none'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['subproducto_id'], ['subproductos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'tipo_cliente', 'cantidad_minima_kg', name='uq_precio_prod_tipo_cantmin'),
    sa.UniqueConstraint('subproducto_id', 'tipo_cliente', 'cantidad_minima_kg', name='uq_precio_subprod_tipo_cantmin')
    )
    with op.batch_alter_table('precios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precios_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_fecha_fin_vigencia'), ['fecha_fin_vigencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_fecha_inicio_vigencia'), ['fecha_inicio_vigencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_subproducto_id'), ['subproducto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_tipo_cliente'), ['tipo_cliente'], unique=False)

    op.create_table('subproducto_modificacion_association',
    sa.Column('subproducto_id', sa.Integer(), nullable=False),
    sa.Column('modificacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modificacion_id'], ['modificaciones.id'], ),
    sa.ForeignKeyConstraint(['subproducto_id'], ['subproductos.id'], ),
    sa.PrimaryKeyConstraint('subproducto_id', 'modificacion_id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('precio_base_kg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_base_kg', sa.FLOAT(), nullable=True))

    op.drop_table('subproducto_modificacion_association')
    with op.batch_alter_table('precios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precios_tipo_cliente'))
        batch_op.drop_index(batch_op.f('ix_precios_subproducto_id'))
        batch_op.drop_index(batch_op.f('ix_precios_producto_id'))
        batch_op.drop_index(batch_op.f('ix_precios_fecha_inicio_vigencia'))
        batch_op.drop_index(batch_op.f('ix_precios_fecha_fin_vigencia'))
        batch_op.drop_index(batch_op.f('ix_precios_activo'))

    op.drop_table('precios')
    with op.batch_alter_table('subproductos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subproductos_producto_padre_id'))
        batch_op.drop_index(batch_op.f('ix_subproductos_nombre'))
        batch_op.drop_index(batch_op.f('ix_subproductos_codigo_subprod'))
        batch_op.drop_index(batch_op.f('ix_subproductos_activo'))

    op.drop_table('subproductos')
    op.drop_table('producto_modificacion_association')
    with op.batch_alter_table('modificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modificaciones_nombre'))
        batch_op.drop_index(batch_op.f('ix_modificaciones_codigo_modif'))
        batch_op.drop_index(batch_op.f('ix_modificaciones_activo'))

    op.drop_table('modificaciones')
    # ### end Alembic commands ###
